### ISSUE TITLE
Add schemas to yazi-rs.github.io/

### ISSUE THREAD

**Issue by uncenter** [yazi-rs/schemas#13]
Not sure the best way to approach this. I think GitHub Pages actually lets us deploy to the yazi-rs.github.io/schemas/ subdirectory since that is the name of this repository, we can give that a test, but I'm not sure if that will work with Docusaurus at the root. Maybe a script to pull in changes on a cron? A redirect? Interested to hear your thoughts @sxyazi.

**Comment by sxyazi** [comment]
I think we need to create a separate branch and place the files from the `schemas` directory in the root of that branch.

Currently, its URL is https://yazi-rs.github.io/schemas/schemas/yazi.schema.json, which is too long. However GitHub pages can only choose between `/` and `/docs` as the website's root directory.

**Comment by uncenter** [comment]
Wait how is it already a URL? How is that working? Yeah it should be https://yazi-rs.github.io/schemas/yazi.json... I can just move the schemas in this repo into the root?

**Comment by sxyazi** [comment]
ahh this is how GitHub pages work, `yazi-rs/yazi-rs.github.io` corresponds to `https://yazi-rs.github.io/`, `yazi-rs/*` corresponds to `https://yazi-rs.github.io/*`, ye you can just move it to the root of this repo.

**Comment by uncenter** [comment]
Oh you don't have to deploy it? So all the files in this repo are at https://yazi-rs.github.io/schemas/? Odd.

**Comment by uncenter** [comment]
Okay so do I put the files in a `gh-pages` branch? I can make a quick workflow to update that branch's files every push?

**Comment by uncenter** [comment]
Oh and on the topic of URLs which do you prefer of the following: 

- `https://yazi-rs.github.io/schemas/yazi.schema.json`
- `https://yazi-rs.github.io/schemas/yazi.json`
- `https://yazi-rs.github.io/schemas/yazi`
- `https://yazi-rs.github.io/schemas/config/yazi`
- `https://yazi-rs.github.io/schemas/yazi-config.json`
- Something else?

**Comment by uncenter** [comment]
https://yazi-rs.github.io/schemas/yazi.json
Got it working! 🎉 
It's deploying after every commit currently, let me know before you release the next Yazi version so I can set it up to only do that when I push a version tag.

**Comment by uncenter** [comment]
(I'll leave this open as a reminder until we get that all setup.)

**Comment by sxyazi** [comment]
Okay, I'll revisit this issue on release!

BTW should we add it to our https://yazi-rs.github.io/docs/configuration/overview page?

**Comment by uncenter** [comment]
We should, but after https://github.com/yazi-rs/yazi-rs.github.io/pull/21 and we should do it when the next release happens since there have been quite a few changes since the last release.

**Comment by sxyazi** [comment]
> let me know before you release the next Yazi version so I can set it up to only do that when I push a version tag.

![dont-matter](https://github.com/yazi-rs/schemas/assets/17523360/2d3d4dc0-cbcf-4264-9bfc-12f8ddebfa91)

**Comment by uncenter** [comment]
Alright, I'll finish up the schemas and let you know!

**Comment by uncenter** [comment]
The schemas should be all set, lint is passing on the latest preset files from the main repo. If you mention the schemas in the release notes maybe say that people should make an issue over here if they find any bugs.

**Comment by sxyazi** [comment]
We should also add it to the docs somewhere!

**Comment by uncenter** [comment]
Definitely! Do you want to or should I?

**Comment by sxyazi** [comment]
Please include it in https://github.com/yazi-rs/yazi-rs.github.io/pull/26, we can merge it at the same time. 😆

**Comment by uncenter** [comment]
Maybe we just add the `"$schema" = "https://yazi-rs.github.io/schemas/CONFIG_FILE_HERE.json"` line to the preset config files?

**Comment by sxyazi** [comment]
Fair enough. Let me add it to the default toml config files.

**Comment by uncenter** [comment]
https://github.com/sxyazi/yazi/pull/506

**Comment by uncenter** [comment]
Do you think this is good to close?
