### ISSUE TITLE
errors after setting .toml /configs 

### ISSUE THREAD

**Issue by Mukulkalsait** [yazi-rs/schemas#27]
i am using WSL2 on windows 11 Dextro = ubuntu-24.04 
i installed .cargo and then yazi 

Every time i try to set config files i get following errors:

Backtrace omitted. Run with RUST_BACKTRACE=1 to display it.
Run with RUST_BACKTRACE=full to include source snippets.

The application panicked (crashed).
  called `Result::unwrap()` on an `Err` value: Error { inner: Error { inner: TomlError { message: "invalid type: string \"<Esc>\", expected a sequence", raw: Some("\"$schema\" = \"https://yazi-rs.github.io/schemas/keymap.json\"\n\n[[manager.keymap]]\non = \"<Esc>\"\nrun = \"escape\"\ndesc = \"Exit visual mode, clear selected, or cancel search\"\n\n[[manager.keymap]]\non = \"<C-[>\"\nrun = \"escape\"\ndesc = \"Exit visual mode, clear selected, or cancel search\"\n\n[[manager.keymap]]\non = \"q\"\nrun = \"quit\"\ndesc = \"Exit the process\"\n\n[[manager.keymap]]\non = \"Q\"\nrun = \"quit --no-cwd-file\"\ndesc = \"Exit the process without writing cwd-file\"\n\n[[manager.keymap]]\non = \"<C-c>\"\nrun = \"close\"\ndesc = \"Close the current tab, or quit if it is last tab\"\n\n[[manager.keymap]]\non = \"<C-z>\"\nrun = \"suspend\"\ndesc = \"Suspend the process\"\n\n[[manager.keymap]]\non = \"k\"\nrun = \"arrow -1\"\ndesc = \"Move cursor up\"\n\n[[manager.keymap]]\non = \"j\"\nrun = \"arrow 1\"\ndesc = \"Move cursor down\"\n\n[[manager.keymap]]\non = \"<Up>\"\nrun = \"arrow -1\"\ndesc = \"Move cursor up\"\n\n[[manager.keymap]]\non = \"<Down>\"\nrun = \"arrow 1\"\ndesc = \"Move cursor down\"\n\n[[manager.keymap]]\non = \"<C-u>\"\nrun = \"arrow -50%\"\ndesc = \"Move cursor up half page\"\n\n[[manager.keymap]]\non = \"<C-d>\"\nrun = \"arrow 50%\"\ndesc = \"Move cursor down half page\"\n\n[[manager.keymap]]\non = \"<C-b>\"\nrun = \"arrow -100%\"\ndesc = \"Move cursor up one page\"\n\n[[manager.keymap]]\non = \"<C-f>\"\nrun = \"arrow 100%\"\ndesc = \"Move cursor down one page\"\n\n[[manager.keymap]]\non = \"<S-PageUp>\"\nrun = \"arrow -50%\"\ndesc = \"Move cursor up half page\"\n\n[[manager.keymap]]\non = \"<S-PageDown>\"\nrun = \"arrow 50%\"\ndesc = \"Move cursor down half page\"\n\n[[manager.keymap]]\non = \"<PageUp>\"\nrun = \"arrow -100%\"\ndesc = \"Move cursor up one page\"\n\n[[manager.keymap]]\non = \"<PageDown>\"\nrun = \"arrow 100%\"\ndesc = \"Move cursor down one page\"\n\n[[manager.keymap]]\non = [\"g\", \"g\"]\nrun = \"arrow -99999999\"\ndesc = \"Move cursor to the top\"\n\n[[manager.keymap]]\non = \"G\"\nrun = \"arrow 99999999\"\ndesc = \"Move cursor to the bottom\"\n\n[[manager.keymap]]\non = \"h\"\nrun = \"leave\"\ndesc = \"Go back to the parent directory\"\n\n[[manager.keymap]]\non = \"l\"\nrun = \"enter\"\ndesc = \"Enter the child directory\"\n\n[[manager.keymap]]\non = \"<Left>\"\nrun = \"leave\"\ndesc = \"Go back to the parent directory\"\n\n[[manager.keymap]]\non = \"<Right>\"\nrun = \"enter\"\ndesc = \"Enter the child directory\"\n\n[[manager.keymap]]\non = \"H\"\nrun = \"back\"\ndesc = \"Go back to the previous directory\"\n\n[[manager.keymap]]\non = \"L\"\nrun = \"forward\"\ndesc = \"Go forward to the next directory\"\n\n[[manager.keymap]]\non = \"K\"\nrun = \"seek -5\"\ndesc = \"Seek up 5 units in the preview\"\n\n[[manager.keymap]]\non = \"J\"\nrun = \"seek 5\"\ndesc = \"Seek down 5 units in the preview\"\n\n[[manager.keymap]]\non = \"<Space>\"\nrun = [\"select --state=none\", \"arrow 1\"]\ndesc = \"Toggle the current selection state\"\n\n[[manager.keymap]]\non = \"v\"\nrun = \"visual_mode\"\ndesc = \"Enter visual mode (selection mode)\"\n\n[[manager.keymap]]\non = \"V\"\nrun = \"visual_mode --unset\"\ndesc = \"Enter visual mode (unset mode)\"\n\n[[manager.keymap]]\non = \"<C-a>\"\nrun = \"select_all --state=true\"\ndesc = \"Select all files\"\n\n[[manager.keymap]]\non = \"<C-r>\"\nrun = \"select_all --state=none\"\ndesc = \"Inverse selection of all files\"\n\n[[manager.keymap]]\non = \"o\"\nrun = \"open\"\ndesc = \"Open selected files\"\n\n[[manager.keymap]]\non = \"O\"\nrun = \"open --interactive\"\ndesc = \"Open selected files interactively\"\n\n[[manager.keymap]]\non = \"<Enter>\"\nrun = \"open\"\ndesc = \"Open selected files\"\n\n[[manager.keymap]]\non = \"<S-Enter>\"\nrun = \"open --interactive\"\ndesc = \"Open selected files interactively\"\n\n[[manager.keymap]]\non = \"y\"\nrun = \"yank\"\ndesc = \"Yank selected files (copy)\"\n\n[[manager.keymap]]\non = \"x\"\nrun = \"yank --cut\"\ndesc = \"Yank selected files (cut)\"\n\n[[manager.keymap]]\non = \"p\"\nrun = \"paste\"\ndesc = \"Paste yanked files\"\n\n[[manager.keymap]]\non = \"P\"\nrun = \"paste --force\"\ndesc = \"Paste yanked files (overwrite if the destination exists)\"\n\n[[manager.keymap]]\non = \"-\"\nrun = \"link\"\ndesc = \"Symlink the absolute path of yanked files\"\n\n[[manager.keymap]]\non = \"_\"\nrun = \"link --relative\"\ndesc = \"Symlink the relative path of yanked files\"\n\n[[manager.keymap]]\non = \"Y\"\nrun = \"unyank\"\ndesc = \"Cancel the yank status\"\n\n[[manager.keymap]]\non = \"X\"\nrun = \"unyank\"\ndesc = \"Cancel the yank status\"\n\n[[manager.keymap]]\non = \"d\"\nrun = \"remove\"\ndesc = \"Trash selected files\"\n\n[[manager.keymap]]\non = \"D\"\nrun = \"remove --permanently\"\ndesc = \"Permanently delete selected files\"\n\n[[manager.keymap]]\non = \"a\"\nrun = \"create\"\ndesc = \"Create a file (ends with / for directories)\"\n\n[[manager.keymap]]\non = \"r\"\nrun = \"rename --cursor=before_ext\"\ndesc = \"Rename selected file(s)\"\n\n[[manager.keymap]]\non = \";\"\nrun = \"shell --interactive\"\ndesc = \"Run a shell command\"\n\n[[manager.keymap]]\non = \":\"\nrun = \"shell --block --interactive\"\ndesc = \"Run a shell command (block until finishes)\"\n\n[[manager.keymap]]\non = \".\"\nrun = \"hidden toggle\"\ndesc = \"Toggle the visibility of hidden files\"\n\n[[manager.keymap]]\non = \"s\"\nrun = \"search fd\"\ndesc = \"Search files by name using fd\"\n\n[[manager.keymap]]\non = \"S\"\nrun = \"search rg\"\ndesc = \"Search files by content using ripgrep\"\n\n[[manager.keymap]]\non = \"<C-s>\"\nrun = \"escape --search\"\ndesc = \"Cancel the ongoing search\"\n\n[[manager.keymap]]\non = \"z\"\nrun = \"plugin zoxide\"\ndesc = \"Jump to a directory using zoxide\"\n\n[[manager.keymap]]\non = \"Z\"\nrun = \"plugin fzf\"\ndesc = \"Jump to a directory or reveal a file using fzf\"\n\n[[manager.keymap]]\non = [\"m\", \"s\"]\nrun = \"linemode size\"\ndesc = \"Set linemode to size\"\n\n[[manager.keymap]]\non = [\"m\", \"p\"]\nrun = \"linemode permissions\"\ndesc = \"Set linemode to permissions\"\n\n[[manager.keymap]]\non = [\"m\", \"c\"]\nrun = \"linemode ctime\"\ndesc = \"Set linemode to ctime\"\n\n[[manager.keymap]]\non = [\"m\", \"m\"]\nrun = \"linemode mtime\"\ndesc = \"Set linemode to mtime\"\n\n[[manager.keymap]]\non = [\"m\", \"o\"]\nrun = \"linemode owner\"\ndesc = \"Set linemode to owner\"\n\n[[manager.keymap]]\non = [\"m\", \"n\"]\nrun = \"linemode none\"\ndesc = \"Set linemode to none\"\n\n[[manager.keymap]]\non = [\"c\", \"c\"]\nrun = \"copy path\"\ndesc = \"Copy the file path\"\n\n[[manager.keymap]]\non = [\"c\", \"d\"]\nrun = \"copy dirname\"\ndesc = \"Copy the directory path\"\n\n[[manager.keymap]]\non = [\"c\", \"f\"]\nrun = \"copy filename\"\ndesc = \"Copy the filename\"\n\n[[manager.keymap]]\non = [\"c\", \"n\"]\nrun = \"copy name_without_ext\"\ndesc = \"Copy the filename without extension\"\n\n[[manager.keymap]]\non = \"f\"\nrun = \"filter --smart\"\ndesc = \"Filter files\"\n\n[[manager.keymap]]\non = \"/\"\nrun = \"find --smart\"\ndesc = \"Find next file\"\n\n[[manager.keymap]]\non = \"?\"\nrun = \"find --previous --smart\"\ndesc = \"Find previous file\"\n\n[[manager.keymap]]\non = \"n\"\nrun = \"find_arrow\"\ndesc = \"Go to the next found\"\n\n[[manager.keymap]]\non = \"N\"\nrun = \"find_arrow --previous\"\ndesc = \"Go to the previous found\"\n\n[[manager.keymap]]\non = [\",\", \"m\"]\nrun = [\"sort modified --reverse=no\", \"linemode mtime\"]\ndesc = \"Sort by modified time\"\n\n[[manager.keymap]]\non = [\",\", \"M\"]\nrun = [\"sort modified --reverse\", \"linemode mtime\"]\ndesc = \"Sort by modified time (reverse)\"\n\n[[manager.keymap]]\non = [\",\", \"c\"]\nrun = [\"sort created --reverse=no\", \"linemode ctime\"]\ndesc = \"Sort by created time\"\n\n[[manager.keymap]]\non = [\",\", \"C\"]\nrun = [\"sort created --reverse\", \"linemode ctime\"]\ndesc = \"Sort by created time (reverse)\"\n\n[[manager.keymap]]\non = [\",\", \"e\"]\nrun = \"sort extension --reverse=no\"\ndesc = \"Sort by extension\"\n\n[[manager.keymap]]\non = [\",\", \"E\"]\nrun = \"sort extension --reverse\"\ndesc = \"Sort by extension (reverse)\"\n\n[[manager.keymap]]\non = [\",\", \"a\"]\nrun = \"sort alphabetical --reverse=no\"\ndesc = \"Sort alphabetically\"\n\n[[manager.keymap]]\non = [\",\", \"A\"]\nrun = \"sort alphabetical --reverse\"\ndesc = \"Sort alphabetically (reverse)\"\n\n[[manager.keymap]]\non = [\",\", \"n\"]\nrun = \"sort natural --reverse=no\"\ndesc = \"Sort naturally\"\n\n[[manager.keymap]]\non = [\",\", \"N\"]\nrun = \"sort natural --reverse\"\ndesc = \"Sort naturally (reverse)\"\n\n[[manager.keymap]]\non = [\",\", \"s\"]\nrun = [\"sort size --reverse=no\", \"linemode size\"]\ndesc = \"Sort by size\"\n\n[[manager.keymap]]\non = [\",\", \"S\"]\nrun = [\"sort size --reverse\", \"linemode size\"]\ndesc = \"Sort by size (reverse)\"\n\n[[manager.keymap]]\non = [\",\", \"r\"]\nrun = \"sort random --reverse=no\"\ndesc = \"Sort randomly\"\n\n[[manager.keymap]]\non = [\"g\", \"h\"]\nrun = \"cd ~\"\ndesc = \"Go to the home directory\"\n\n[[manager.keymap]]\non = [\"g\", \"c\"]\nrun = \"cd ~/.config\"\ndesc = \"Go to the config directory\"\n\n[[manager.keymap]]\non = [\"g\", \"d\"]\nrun = \"cd ~/Downloads\"\ndesc = \"Go to the downloads directory\"\n\n[[manager.keymap]]\non = [\"g\", \"<Space>\"]\nrun = \"cd --interactive\"\ndesc = \"Go to a directory interactively\"\n\n[[manager.keymap]]\non = \"t\"\nrun = \"tab_create --current\"\ndesc = \"Create a new tab with CWD\"\n\n[[manager.keymap]]\non = \"1\"\nrun = \"tab_switch 0\"\ndesc = \"Switch to the first tab\"\n\n[[manager.keymap]]\non = \"2\"\nrun = \"tab_switch 1\"\ndesc = \"Switch to the second tab\"\n\n[[manager.keymap]]\non = \"3\"\nrun = \"tab_switch 2\"\ndesc = \"Switch to the third tab\"\n\n[[manager.keymap]]\non = \"4\"\nrun = \"tab_switch 3\"\ndesc = \"Switch to the fourth tab\"\n\n[[manager.keymap]]\non = \"5\"\nrun = \"tab_switch 4\"\ndesc = \"Switch to the fifth tab\"\n\n[[manager.keymap]]\non = \"6\"\nrun = \"tab_switch 5\"\ndesc = \"Switch to the sixth tab\"\n\n[[manager.keymap]]\non = \"7\"\nrun = \"tab_switch 6\"\ndesc = \"Switch to the seventh tab\"\n\n[[manager.keymap]]\non = \"8\"\nrun = \"tab_switch 7\"\ndesc = \"Switch to the eighth tab\"\n\n[[manager.keymap]]\non = \"9\"\nrun = \"tab_switch 8\"\ndesc = \"Switch to the ninth tab\"\n\n[[manager.keymap]]\non = \"[\"\nrun = \"tab_switch -1 --relative\"\ndesc = \"Switch to the previous tab\"\n\n[[manager.keymap]]\non = \"]\"\nrun = \"tab_switch 1 --relative\"\ndesc = \"Switch to the next tab\"\n\n[[manager.keymap]]\non = \"{\"\nrun = \"tab_swap -1\"\ndesc = \"Swap current tab with previous tab\"\n\n[[manager.keymap]]\non = \"}\"\nrun = \"tab_swap 1\"\ndesc = \"Swap current tab with next tab\"\n\n[[manager.keymap]]\non = \"w\"\nrun = \"tasks_show\"\ndesc = \"Show task manager\"\n\n[[manager.keymap]]\non = \"~\"\nrun = \"help\"\ndesc = \"Open help\"\n\n[[manager.keymap]]\non = \"<F1>\"\nrun = \"help\"\ndesc = \"Open help\"\n\n[[tasks.keymap]]\non = \"<Esc>\"\nrun = \"close\"\ndesc = \"Close task manager\"\n\n[[tasks.keymap]]\non = \"<C-[>\"\nrun = \"close\"\ndesc = \"Close task manager\"\n\n[[tasks.keymap]]\non = \"<C-c>\"\nrun = \"close\"\ndesc = \"Close task manager\"\n\n[[tasks.keymap]]\non = \"w\"\nrun = \"close\"\ndesc = \"Close task manager\"\n\n[[tasks.keymap]]\non = \"k\"\nrun = \"arrow -1\"\ndesc = \"Move cursor up\"\n\n[[tasks.keymap]]\non = \"j\"\nrun = \"arrow 1\"\ndesc = \"Move cursor down\"\n\n[[tasks.keymap]]\non = \"<Up>\"\nrun = \"arrow -1\"\ndesc = \"Move cursor up\"\n\n[[tasks.keymap]]\non = \"<Down>\"\nrun = \"arrow 1\"\ndesc = \"Move cursor down\"\n\n[[tasks.keymap]]\non = \"<Enter>\"\nrun = \"inspect\"\ndesc = \"Inspect the task\"\n\n[[tasks.keymap]]\non = \"x\"\nrun = \"cancel\"\ndesc = \"Cancel the task\"\n\n[[tasks.keymap]]\non = \"~\"\nrun = \"help\"\ndesc = \"Open help\"\n\n[[tasks.keymap]]\non = \"<F1>\"\nrun = \"help\"\ndesc = \"Open help\"\n\n[[select.keymap]]\non = \"<Esc>\"\nrun = \"close\"\ndesc = \"Cancel selection\"\n\n[[select.keymap]]\non = \"<C-[>\"\nrun = \"close\"\ndesc = \"Cancel selection\"\n\n[[select.keymap]]\non = \"<C-c>\"\nrun = \"close\"\ndesc = \"Cancel selection\"\n\n[[select.keymap]]\non = \"<Enter>\"\nrun = \"close --submit\"\ndesc = \"Submit the selection\"\n\n[[select.keymap]]\non = \"k\"\nrun = \"arrow -1\"\ndesc = \"Move cursor up\"\n\n[[select.keymap]]\non = \"j\"\nrun = \"arrow 1\"\ndesc = \"Move cursor down\"\n\n[[select.keymap]]\non = \"<Up>\"\nrun = \"arrow -1\"\ndesc = \"Move cursor up\"\n\n[[select.keymap]]\non = \"<Down>\"\nrun = \"arrow 1\"\ndesc = \"Move cursor down\"\n\n[[select.keymap]]\non = \"~\"\nrun = \"help\"\ndesc = \"Open help\"\n\n[[select.keymap]]\non = \"<F1>\"\nrun = \"help\"\ndesc = \"Open help\"\n\n[[input.keymap]]\non = \"<C-c>\"\nrun = \"close\"\ndesc = \"Cancel input\"\n\n[[input.keymap]]\non = \"<Enter>\"\nrun = \"close --submit\"\ndesc = \"Submit the input\"\n\n[[input.keymap]]\non = \"<Esc>\"\nrun = \"escape\"\ndesc = \"Go back the normal mode, or cancel input\"\n\n[[input.keymap]]\non = \"<C-[>\"\nrun = \"escape\"\ndesc = \"Go back the normal mode, or cancel input\"\n\n[[input.keymap]]\non = \"i\"\nrun = \"insert\"\ndesc = \"Enter insert mode\"\n\n[[input.keymap]]\non = \"a\"\nrun = \"insert --append\"\ndesc = \"Enter append mode\"\n\n[[input.keymap]]\non = \"I\"\nrun = [\"move -999\", \"insert\"]\ndesc = \"Move to the BOL, and enter insert mode\"\n\n[[input.keymap]]\non = \"A\"\nrun = [\"move 999\", \"insert --append\"]\ndesc = \"Move to the EOL, and enter append mode\"\n\n[[input.keymap]]\non = \"v\"\nrun = \"visual\"\ndesc = \"Enter visual mode\"\n\n[[input.keymap]]\non = \"V\"\nrun = [\"move -999\", \"visual\", \"move 999\"]\ndesc = \"Enter visual mode and select all\"\n\n[[input.keymap]]\non = \"h\"\nrun = \"move -1\"\ndesc = \"Move back a character\"\n\n[[input.keymap]]\non = \"l\"\nrun = \"move 1\"\ndesc = \"Move forward a character\"\n\n[[input.keymap]]\non = \"<Left>\"\nrun = \"move -1\"\ndesc = \"Move back a character\"\n\n[[input.keymap]]\non = \"<Right>\"\nrun = \"move 1\"\ndesc = \"Move forward a character\"\n\n[[input.keymap]]\non = \"<C-b>\"\nrun = \"move -1\"\ndesc = \"Move back a character\"\n\n[[input.keymap]]\non = \"<C-f>\"\nrun = \"move 1\"\ndesc = \"Move forward a character\"\n\n[[input.keymap]]\non = \"b\"\nrun = \"backward\"\ndesc = \"Move back to the start of the current or previous word\"\n\n[[input.keymap]]\non = \"w\"\nrun = \"forward\"\ndesc = \"Move forward to the start of the next word\"\n\n[[input.keymap]]\non = \"e\"\nrun = \"forward --end-of-word\"\ndesc = \"Move forward to the end of the current or next word\"\n\n[[input.keymap]]\non = \"<A-b>\"\nrun = \"backward\"\ndesc = \"Move back to the start of the current or previous word\"\n\n[[input.keymap]]\non = \"<A-f>\"\nrun = \"forward --end-of-word\"\ndesc = \"Move forward to the end of the current or next word\"\n\n[[input.keymap]]\non = \"0\"\nrun = \"move -999\"\ndesc = \"Move to the BOL\"\n\n[[input.keymap]]\non = \"$\"\nrun = \"move 999\"\ndesc = \"Move to the EOL\"\n\n[[input.keymap]]\non = \"<C-a>\"\nrun = \"move -999\"\ndesc = \"Move to the BOL\"\n\n[[input.keymap]]\non = \"<C-e>\"\nrun = \"move 999\"\ndesc = \"Move to the EOL\"\n\n[[input.keymap]]\non = \"<Home>\"\nrun = \"move -999\"\ndesc = \"Move to the BOL\"\n\n[[input.keymap]]\non = \"<End>\"\nrun = \"move 999\"\ndesc = \"Move to the EOL\"\n\n[[input.keymap]]\non = \"<Backspace>\"\nrun = \"backspace\"\ndesc = \"Delete the character before the cursor\"\n\n[[input.keymap]]\non = \"<Delete>\"\nrun = \"backspace --under\"\ndesc = \"Delete the character under the cursor\"\n\n[[input.keymap]]\non = \"<C-h>\"\nrun = \"backspace\"\ndesc = \"Delete the character before the cursor\"\n\n[[input.keymap]]\non = \"<C-d>\"\nrun = \"backspace --under\"\ndesc = \"Delete the character under the cursor\"\n\n[[input.keymap]]\non = \"<C-u>\"\nrun = \"kill bol\"\ndesc = \"Kill backwards to the BOL\"\n\n[[input.keymap]]\non = \"<C-k>\"\nrun = \"kill eol\"\ndesc = \"Kill forwards to the EOL\"\n\n[[input.keymap]]\non = \"<C-w>\"\nrun = \"kill backward\"\ndesc = \"Kill backwards to the start of the current word\"\n\n[[input.keymap]]\non = \"<A-d>\"\nrun = \"kill forward\"\ndesc = \"Kill forwards to the end of the current word\"\n\n[[input.keymap]]\non = \"d\"\nrun = \"delete --cut\"\ndesc = \"Cut the selected characters\"\n\n[[input.keymap]]\non = \"D\"\nrun = [\"delete --cut\", \"move 999\"]\ndesc = \"Cut until the EOL\"\n\n[[input.keymap]]\non = \"c\"\nrun = \"delete --cut --insert\"\ndesc = \"Cut the selected characters, and enter insert mode\"\n\n[[input.keymap]]\non = \"C\"\nrun = [\"delete --cut --insert\", \"move 999\"]\ndesc = \"Cut until the EOL, and enter insert mode\"\n\n[[input.keymap]]\non = \"x\"\nrun = [\"delete --cut\", \"move 1 --in-operating\"]\ndesc = \"Cut the current character\"\n\n[[input.keymap]]\non = \"y\"\nrun = \"yank\"\ndesc = \"Copy the selected characters\"\n\n[[input.keymap]]\non = \"p\"\nrun = \"paste\"\ndesc = \"Paste the copied characters after the cursor\"\n\n[[input.keymap]]\non = \"P\"\nrun = \"paste --before\"\ndesc = \"Paste the copied characters before the cursor\"\n\n[[input.keymap]]\non = \"u\"\nrun = \"undo\"\ndesc = \"Undo the last operation\"\n\n[[input.keymap]]\non = \"<C-r>\"\nrun = \"redo\"\ndesc = \"Redo the last operation\"\n\n[[input.keymap]]\non = \"~\"\nrun = \"help\"\ndesc = \"Open help\"\n\n[[input.keymap]]\non = \"<F1>\"\nrun = \"help\"\ndesc = \"Open help\"\n\n[[completion.keymap]]\non = \"<C-c>\"\nrun = \"close\"\ndesc = \"Cancel completion\"\n\n[[completion.keymap]]\non = \"<Tab>\"\nrun = \"close --submit\"\ndesc = \"Submit the completion\"\n\n[[completion.keymap]]\non = \"<Enter>\"\nrun = [\"close --submit\", \"close_input --submit\"]\ndesc = \"Submit the completion and input\"\n\n[[completion.keymap]]\non = \"<A-k>\"\nrun = \"arrow -1\"\ndesc = \"Move cursor up\"\n\n[[completion.keymap]]\non = \"<A-j>\"\nrun = \"arrow 1\"\ndesc = \"Move cursor down\"\n\n[[completion.keymap]]\non = \"<Up>\"\nrun = \"arrow -1\"\ndesc = \"Move cursor up\"\n\n[[completion.keymap]]\non = \"<Down>\"\nrun = \"arrow 1\"\ndesc = \"Move cursor down\"\n\n[[completion.keymap]]\non = \"<C-p>\"\nrun = \"arrow -1\"\ndesc = \"Move cursor up\"\n\n[[completion.keymap]]\non = \"<C-n>\"\nrun = \"arrow 1\"\ndesc = \"Move cursor down\"\n\n[[completion.keymap]]\non = \"~\"\nrun = \"help\"\ndesc = \"Open help\"\n\n[[completion.keymap]]\non = \"<F1>\"\nrun = \"help\"\ndesc = \"Open help\"\n\n[[help.keymap]]\non = \"<Esc>\"\nrun = \"escape\"\ndesc = \"Clear the filter, or hide the help\"\n\n[[help.keymap]]\non = \"<C-[>\"\nrun = \"escape\"\ndesc = \"Clear the filter, or hide the help\"\n\n[[help.keymap]]\non = \"q\"\nrun = \"close\"\ndesc = \"Exit the process\"\n\n[[help.keymap]]\non = \"<C-c>\"\nrun = \"close\"\ndesc = \"Hide the help\"\n\n[[help.keymap]]\non = \"k\"\nrun = \"arrow -1\"\ndesc = \"Move cursor up\"\n\n[[help.keymap]]\non = \"j\"\nrun = \"arrow 1\"\ndesc = \"Move cursor down\"\n\n[[help.keymap]]\non = \"<Up>\"\nrun = \"arrow -1\"\ndesc = \"Move cursor up\"\n\n[[help.keymap]]\non = \"<Down>\"\nrun = \"arrow 1\"\ndesc = \"Move cursor down\"\n\n[[help.keymap]]\non = \"f\"\nrun = \"filter\"\ndesc = \"Apply a filter for the help items\"\n"), keys: ["manager", "keymap", "on"], span: Some(85..92) } } }
in /home/mukul-dk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yazi-config-0.2.5/src/keymap/keymap.rs, line 67
thread: main

Even if i remove keymap.toml file i get same kind with theme.toml file. and yazi.toml file dosent work at all.

Thankyou.

**Comment by uncenter** [comment]
Can you share your configuration file? This isn't an issue with the schemas, this is an issue with Yazi parsing your configuration. cc @sxyazi can you transfer this to the main repository?

**Comment by sxyazi** [comment]
Hey @Mukulkalsait, please create a bug report using https://github.com/sxyazi/yazi/issues/new?assignees=&labels=bug&projects=&template=bug.yml and complete the template so that I have enough information to further investigate your issue. I apologize for any inconvenience caused!

Closing as it seems not a scheme problem
