### ISSUE TITLE
prepend and append rules keys missing in `open` section

### ISSUE THREAD

**Issue by ValdezFOmar** [yazi-rs/schemas#28]
The [docs](https://yazi-rs.github.io/docs/configuration/yazi/#open) mentioned that I can use `prepend_rules` and `append_rules` keys in `[open]`, but this are not present on the [schema](https://github.com/yazi-rs/schemas/blob/0464707359cf5b39273560be7d9e0a731270867c/schemas/yazi.json#L93C5-L93C15):

![image](https://github.com/user-attachments/assets/fda12dfb-50c2-4119-b5c4-ac6ab6ab2b0f)

**Comment by sxyazi** [comment]
I can confirm that they are indeed missing from the [scheme](https://github.com/yazi-rs/schemas/blob/0464707359cf5b39273560be7d9e0a731270867c/schemas/yazi.json#L91).

Would you like to raise a PR for it?

**Comment by ValdezFOmar** [comment]
Sure, no problem
